// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUm1RbpecOz75UgDjFh64eUTOfwu-6pY8',
    appId: '1:564547243693:web:a8c46c57affd1125db8024',
    messagingSenderId: '564547243693',
    projectId: 'mws-tubes',
    authDomain: 'mws-tubes.firebaseapp.com',
    storageBucket: 'mws-tubes.firebasestorage.app',
    measurementId: 'G-HBN2Z311E1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7hlUbqbUsnMAZ3FfhvSMVbyL3QrhoU48',
    appId: '1:564547243693:android:65e1b1c72f6054a9db8024',
    messagingSenderId: '564547243693',
    projectId: 'mws-tubes',
    storageBucket: 'mws-tubes.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkoYQ3xDHstv3Yjg7K79PSqUeK7rb8iYk',
    appId: '1:564547243693:ios:33a568ba38c159d3db8024',
    messagingSenderId: '564547243693',
    projectId: 'mws-tubes',
    storageBucket: 'mws-tubes.firebasestorage.app',
    iosBundleId: 'com.example.tugasbesar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkoYQ3xDHstv3Yjg7K79PSqUeK7rb8iYk',
    appId: '1:564547243693:ios:33a568ba38c159d3db8024',
    messagingSenderId: '564547243693',
    projectId: 'mws-tubes',
    storageBucket: 'mws-tubes.firebasestorage.app',
    iosBundleId: 'com.example.tugasbesar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUm1RbpecOz75UgDjFh64eUTOfwu-6pY8',
    appId: '1:564547243693:web:e930f427b30f8b4bdb8024',
    messagingSenderId: '564547243693',
    projectId: 'mws-tubes',
    authDomain: 'mws-tubes.firebaseapp.com',
    storageBucket: 'mws-tubes.firebasestorage.app',
    measurementId: 'G-RGFYC6N7W7',
  );
}
